# Generated by Django 2.1.4 on 2019-01-04 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProductBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField(default=True)),
                ('female', models.BooleanField(default=True)),
                ('height', models.IntegerField(default=60)),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=85)),
                ('min_weight', models.IntegerField(default=0)),
                ('max_weight', models.IntegerField(default=450)),
                ('product_type', models.CharField(default='undefined', max_length=200)),
                ('carrier', models.CharField(default='Carrier', max_length=200)),
                ('product2', models.CharField(default='', max_length=200)),
                ('product3', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='undefined', max_length=200)),
                ('time', models.CharField(default='undefined', max_length=200)),
                ('indication', models.CharField(default='undefined', max_length=200)),
                ('outcome', models.CharField(default='undefined', max_length=200)),
                ('product', models.CharField(default='undefined', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(default=0)),
                ('under1', models.CharField(max_length=200)),
                ('one_4', models.CharField(max_length=200)),
                ('five_9', models.CharField(max_length=200)),
                ('ten_14', models.CharField(max_length=200)),
                ('fifteen_24', models.CharField(max_length=200)),
                ('twofive_34', models.CharField(max_length=200)),
                ('threefive_44', models.CharField(max_length=200)),
                ('fourfive_54', models.CharField(max_length=200)),
                ('fivefive_64', models.CharField(max_length=200)),
                ('over65', models.CharField(max_length=200)),
                ('Total', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMetric',
            fields=[
                ('humanmetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.HumanMetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('insurance.humanmetric',),
        ),
    ]
