# Generated by Django 2.1.4 on 2019-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanmetric',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
