# Generated by Django 2.1.4 on 2019-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_humanmetric_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(default=0)),
                ('under1', models.CharField(max_length=200)),
                ('one_4', models.CharField(max_length=200)),
                ('five_9', models.CharField(max_length=200)),
                ('ten_14', models.CharField(max_length=200)),
                ('fifteen_24', models.CharField(max_length=200)),
                ('twofive_34', models.CharField(max_length=200)),
                ('threefive_44', models.CharField(max_length=200)),
                ('fourfive_54', models.CharField(max_length=200)),
                ('fivefive_64', models.CharField(max_length=200)),
                ('over65', models.CharField(max_length=200)),
                ('Total', models.CharField(max_length=200)),
            ],
        ),
    ]
