# Generated by Django 2.1.4 on 2019-01-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_topdeath'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProductBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField(default=True)),
                ('female', models.BooleanField(default=True)),
                ('height', models.IntegerField(default=60)),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=85)),
                ('min_weight', models.IntegerField(default=0)),
                ('max_weight', models.IntegerField(default=450)),
                ('product_type', models.CharField(default='undefined', max_length=200)),
                ('carrier', models.CharField(default='Carrier', max_length=200)),
                ('product2', models.CharField(default='', max_length=200)),
                ('product3', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
