# Generated by Django 2.1.4 on 2019-01-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insuranceproductbuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='undefined', max_length=200)),
                ('time', models.CharField(default='undefined', max_length=200)),
                ('indication', models.CharField(default='undefined', max_length=200)),
                ('outcome', models.CharField(default='undefined', max_length=200)),
                ('carrier', models.CharField(default='undefined', max_length=200)),
                ('product2', models.CharField(default='', max_length=200)),
                ('product3', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
